### ISSUE TITLE
Fetch Prefect details from CoordinatorType

### ISSUE THREAD

**Issue by riteshsp2000** [dscnitrourkela/project-avocado-web#23]
**Is your feature request related to a problem? Please describe.**
- Currently, the PrefectType can display the coordinator related with the particular prefect. A similar thing is to be done with CoordinatorType. Add a field to display the corresponding prefect.

**Describe the solution you'd like**
- Add a field in the Coordinator Schema to store prefect id. 
- In the Coordinator field use this prefect id to fetch the prefect details

**Comment by JWhacheng** [comment]
Hey @riteshsp2000 I would like to do this.

**Comment by DesignrKnight** [comment]
Hello, @JWhacheng 
Any updates?

**Comment by JWhacheng** [comment]
Hello @DesignrKnight I had some problems with my GitHub accout. I just reolved. I am making the pull request today at nigh.

**Comment by DesignrKnight** [comment]
Totally understand. No issues. Hope everything is good now. Saw your PR, will review
