### ISSUE TITLE
Split Schema.js file into Types, Queries and Mutations files

### ISSUE THREAD

**Issue by riteshsp2000** [dscnitrourkela/project-avocado-web#24]
- Currently all the types, root queries, mutations are placed inside a single schema.js file.
- Separate this file into 3 different files for queries, mutations, types respectively.
- Import all three files inside Schema.js and export the GraphQLSchema from here itself.

**Comment by justemoilouise** [comment]
hi, i'd like to take on this :)

**Comment by DesignrKnight** [comment]
That was fast @justemoilouise. We request you to wait for one of the maintainers to assign/confirm before you start working as we want to make sure your contributions can be merged easily. 

Thanks again for your contribution
